[project]
name = "riemannian-diffusion-mixture-torch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = [
    "accelerate>=1.12.0",
    "biopython>=1.85",
    "biotite>=1.5.0",
    "cartopy>=0.25.0",
    "dotenv>=0.9.9",
    "fsspec[http]>=2021.5.0,!=2021.6.0",
    "hydra-colorlog>=1.2.0",
    "hydra-core>=1.3.0",
    "hydra-joblib-launcher>=1.2.0",
    "joblib>=1.5.2",
    "libigl>=2.6.1",
    "matplotlib>=3.10.7",
    "mlflow>=3.6.0",
    "nglview>=3.1.4",
    "numpy>=2.3.3",
    "openmm>=8.4.0.post1",
    "plotly>=6.3.1",
    "pytorch-lightning>=2.5.6",
    "pyvista>=0.46.3",
    "seaborn>=0.13.2",
    "torchdiffeq>=0.2.5",
    "tqdm>=4.67.1",
    "transformers>=4.57.1",
    "wandb>=0.23.0",
    "weave>=0.52.17",
]
